### ISSUE TITLE
Canvas block

### ISSUE THREAD

**Issue by bend-n** [KosmosPrime/plandustry#3]
The [canvas block](https://github.com/Anuken/Mindustry/blob/37e138858b7a3c660173826b6a310b23e181e5ff/core/src/mindustry/world/blocks/logic/CanvasBlock.java) is not currently implemented.

Im not sure where you get your `deserialize_state` implementation from, so im unsure as to create it myself. Could you explain perhaps?

**Comment by KosmosPrime** [comment]
I've not implemented erekir blocks as I've found blueprints on that planet to be rather unsatisfying. The logic blocks are defined in [logic.rs](https://github.com/KosmosPrime/plandustry/blob/master/src/block/logic.rs), I believe blueprints don't store any display state so adding it is a one-liner.

**Comment by bend-n** [comment]
Canvas blocks do store state though, so I think its not as simple as 
```rs
CANVAS: "canvas" => SimpleBlock::new(3, true, cost!(Silicon: 30, Beryllium: 10));
```

**Comment by bend-n** [comment]
I figured [it out](https://github.com/bend-n/mindus/pull/5/commits/f028c1795fa04b816bab5a496b13a305d5c459a0#diff-a5e86af97c54d02ebbe0d7b64e27bace1d95ffc3b4c48599aba033ca288932e7R77)
